#!/usr/bin/env python3
"""Generate build_info.py with build metadata for GitHub Actions."""
import subprocess
import datetime
import sys


def get_git_info():
    """Gather git and build information."""
    def run_git(cmd):
        try:
            return subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode().strip()
        except Exception:
            return "unknown"

    return {
        'commit_hash': run_git(['git', 'rev-parse', 'HEAD']),
        'commit_short': run_git(['git', 'rev-parse', '--short', 'HEAD']),
        'branch': run_git(['git', 'rev-parse', '--abbrev-ref', 'HEAD']),
        'commit_message': run_git(['git', 'log', '-1', '--pretty=%s']),
        'build_date': datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC'),
        'tag': run_git(['git', 'describe', '--tags', '--always']),
    }


def generate_info_module(output_path='build_info.py'):
    """Write build info as an importable Python module."""
    info = get_git_info()
    with open(output_path, 'w') as f:
        f.write('# Auto-generated by commit_info.py - do not edit\n')
        for key, value in info.items():
            escaped = value.replace('\\', '\\\\').replace('"', '\\"')
            f.write(f'{key} = "{escaped}"\n')


if __name__ == '__main__':
    output = sys.argv[1] if len(sys.argv) > 1 else 'build_info.py'
    generate_info_module(output)
    print(f"Build info written to {output}")
